language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-33
    - android-33
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

notifications:
  email: false
